version: "3.7"
services:
    nginx:
      build:
        context: ./localNginx #ローカル開発用です。HTTPSポートは公開しません 
        dockerfile: Dockerfile
      ports:
          - target: 80
            published: 8080
            protocol: tcp
      volumes:
          - ./logs/nginx_access.log:/var/log/nginx/da_access.log
    backend:
      init: true
      build:
        context: ../development/backend
        dockerfile: Dockerfile
    frontend:
      build:
        context: ./dummyFrontend #dummyFrontendはダミーのhtmlのみ返却します。
        dockerfile: Dockerfile
    mysql:
      build:
        context: ./localMysql
        dockerfile: Dockerfile
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_DATABASE: "app"
        MYSQL_USER: "backend"
        MYSQL_PASSWORD : "backend"
      ports:
          - "3306:3306"
      volumes:
          - ./logs/mysql_slow.log:/var/log/slow.log
    locust:
        image: locustio/locust
        ports:
          - "8089:8089"
        volumes:
          - ./localLocust/:/mnt/locust
        command: --config /mnt/locust/locust.conf.org
